project:
  type: website

website:
  site-url: "https://epiverse-trace.github.io/blog"
  title: "Epiverse-Trace technical blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/DataDotOrg
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
