on:
  workflow_dispatch:
  pull_request:
    branches: [main]

name: Deploy Preview

jobs:
  build-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Render 
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: html

      - name: Deploy Preview to Netlify as preview
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v2
        env:
          NETLIFY_SITE_ID: 2a3da659-672b-4e5b-8785-e10ebf79a962
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          publish-dir: './_site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          alias: deploy-preview-${{ github.event.number }}
          # these all default to 'true'
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        timeout-minutes: 1